# Generated by Django 5.0.3 on 2024-03-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0005_alter_artist_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="listened",
            field=models.IntegerField(default=0),
        ),
    ]
